#!/usr/bin/env python3

from argparse import Namespace, ArgumentParser
from engine.suggest import suggest
from engine.ranking import search


class Parser:
    """Parser that retreives the search term, category, and top number of results from the command line arguments."""

    def __init__(self):
        args = self._get_args()
        self.search: str = args.search[0]
        self.category: str | None = args.category
        self.top: int = args.top

    def _get_args(self) -> Namespace:
        parser = ArgumentParser()
        parser.add_argument("search", type=str, nargs="+")
        parser.add_argument("-c", "--category", type=str)
        parser.add_argument("-t", "--top", type=int, default=10)
        args, unknown = parser.parse_known_args()
        return args


if __name__ == "__main__":
    parser = Parser()
    print(f"Results for: {parser.search}")
    search_results = search(parser.search, top_k=parser.top)

    if not search_results:
        print("No results found.")
        print("Did you mean:")
        suggestions = suggest(parser.search, max_suggestions=3)
        for word in parser.search.split(" "):
            suggestions = suggest(word, max_suggestions=3)
            print(f"{word} -> {", ".join(suggestions)}")
    else:
        for i, search_result in enumerate(search_results):
            print(f"{i + 1}. [{search_result["id"]}] {search_result["name"]}")
            print(f"{search_result["category"]}")
            print(
                f"€{search_result["price"]} | {search_result["stock"]} in stock | rank #{search_result["sales_rank"]}"
            )
            print("")
